ActiveAdmin.register Page do
  menu :label => 'Pages', :parent => 'Pages'
  
  filter :name
  filter :published

  index do
    column :id
    column :name
    column :navigation_name
    column :published
    
    actions
  end
  
  form do |f|
    f.inputs "Page Info" do
      f.input :name
      f.input :navigation_name, :hint => 'This name will show up in UI'
      f.input :description
      f.input :slug, :hint => 'The name used to access the page. Autogenerated if left blank'
      f.input :published, :hint => 'Only published pages will show up in UI'
    end
    
    f.inputs "Page Content" do
      f.input :title
      f.input :content
    end
    
    f.actions
  end
end
