MAIL_SMTP_HOST = ENV["MAIL_SMTP_HOST"]
MAIL_SMTP_PORT = ENV["MAIL_SMTP_PORT"]
MAIL_SMTP_USER = ENV["MAIL_SMTP_USER"]
MAIL_SMTP_PASS = ENV["MAIL_SMTP_PASS"]
MAIL_SMTP_AUTHENTICATION = :plain
MAIL_SMTP_DOMAIN = ENV["MAIL_SMTP_DOMAIN"]
